@host = http://localhost:3000

### Register
POST {{host}}/api/auth/register
Content-Type: application/json

{
  "email": "ana@example.com",
  "username": "ana",
  "password": "parola123"
}

### Login
POST {{host}}/api/auth/login
Content-Type: application/json

{
  "email": "tudor@example.com",
  "password": "parola123"
}

### Send friend request
POST {{host}}/api/friends/requests
Content-Type: application/json

{ "target": "tudorm" }