@host = http://localhost:3000

### Register
POST {{host}}/api/auth/register
Content-Type: application/json

{
  "email": "tudor@example.com",
  "username": "tudorm",
  "password": "parola123"
}

### Login
POST {{host}}/api/auth/login
Content-Type: application/json

{
  "email": "tudor@example.com",
  "password": "parola123"
}